# fly.toml app configuration file
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "aulelibere-polimi"
primary_region = "ams"  # Amsterdam - closest to Italy

[build]

[env]
  USE_WEBHOOK = "true"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false  # Keep always running
  auto_start_machines = true
  min_machines_running = 1     # Always keep 1 machine running

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
